apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: demo-app-backup-policy
  namespace: kasten-io
spec:
  comment: Backup policy for the demo-app
  frequency: "@hourly"
  retention:
    hourly: 24
    daily: 7
  actions:
    - action: backup
    # - action: export
    #   exportParameters:
    #     frequency: "@hourly"
    #     migrationToken:
    #       name: ""
    #       namespace: ""
    #     profile:
    #       name: s3-export
    #       namespace: kasten-io
    #     receiveString: ""
    #     exportData:
    #       enabled: true
    #   retention:
    #     hourly: 0
    #     daily: 0
    #     weekly: 0
    #     monthly: 0
    #     yearly: 0
  selector:
    matchLabels:
      k10.kasten.io/appNamespace: demo-app
